_commit: 0.8.0
_src_path: gh:georgedouzas/copier-pdm-nox.git
author_email: gdouzas@icloud.com
author_fullname: Georgios Douzas
author_username: georgedouzas
copyright_date: '2023'
copyright_holder: Georgios Douzas
copyright_holder_email: gdouzas@icloud.com
copyright_license: MIT License
project_description: AI composability. Modular solutions from supervised learning
    to deep, reinforcement, and neurosymbolic AI, supporting a wide range of applications.
python_package_distribution_name: brainblocks
python_package_import_name: brainblocks
python_versions: '>=3.9, <3.12'
repository_name: brainblocks
repository_namespace: brainblocks

