_commit: 0.10.0
_src_path: gh:georgedouzas/copier-pdm-nox.git
author_email: gdouzas@icloud.com
author_fullname: Georgios Douzas
author_username: georgedouzas
copyright_date: '2024'
copyright_holder: Georgios Douzas
copyright_holder_email: gdouzas@icloud.com
copyright_license: MIT License
project_description: A library designed to extend skorch for Reinforcement Learning
    problems, maintaining the simplicity of scikit-learn's API. It integrates torchrl,
    and leverages textgrad, DSPy, and DocArray for enhanced functionality​.
python_package_distribution_name: skorch-rl
python_package_import_name: srl
python_versions: '>=3.9, <3.13'
repository_name: skorch-rl
repository_namespace: BrainBlocksAI

